---
language: go
env:
  - GO111MODULE=on
go:
  - "1.12.x"

script:
  - wget https://github.com/kubernetes-sigs/kubebuilder/releases/download/v1.0.8/kubebuilder_1.0.8_linux_amd64.tar.gz
  - tar xvzf kubebuilder_1.0.8_linux_amd64.tar.gz
  - mkdir -p /usr/local/kubebuilder/bin
  - cp kubebuilder_1.0.8_linux_amd64/bin/* /usr/local/kubebuilder/bin/
  - make test

# calls goreleaser
deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux
