
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- resources:
  - nodes/status
  verbs:
  - get
- apiGroups:
  - openstack.repl.info
  resources:
  - events
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - openstack.repl.info
  resources:
  - securitygroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openstack.repl.info
  resources:
  - securitygroups/status
  verbs:
  - get
  - patch
  - update
