# permissions to do viewer securitygroups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: securitygroup-viewer-role
rules:
- apiGroups:
  - openstack.repl.info
  resources:
  - securitygroups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - openstack.repl.info
  resources:
  - securitygroups/status
  verbs:
  - get
