# permissions to do edit securitygroups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: securitygroup-editor-role
rules:
- apiGroups:
  - openstack.repl.info
  resources:
  - securitygroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openstack.repl.info
  resources:
  - securitygroups/status
  verbs:
  - get
  - patch
  - update
