apiVersion: openstack.repl.info/v1beta1
kind: SecurityGroup
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: securitygroup-sample
spec:
  nodeSelector:
    role: master
  name: sg-test
  rules:
    - direction: "ingress"
      portRangeMax: 8888
      portRangeMin: 8888
      remoteIpPrefix: "127.0.0.1/32"
      etherType: "IPv4"
      protocol: "tcp"